# Copyright (c) 2024 Jason Kridner <jkridner@beagleboard.org>
# SPDX-License-Identifier: Apache-2.0

manifest:
  self:
    west-commands: scripts/west-commands.yml

  remotes:
    - name: upstream
      url-base: https://github.com/zephyrproject-rtos
    - name: jadonk
      url-base: https://github.com/jadonk

  projects:
    - name: zephyr-1
      remote: jadonk
      path: zephyr
      revision: pm-fixes
      import:
        name-allowlist:
          - hal_ti
          - cmsis_6
          - cmsis-dsp
          - mcuboot
          - mbedtls
          - zcbor
